"""Joint likelihood calibration via per-channel temperature scaling.

The vanilla PRISM update treats the four evidence channels (stage1, stage2,
and up to three specialists) as conditionally independent given tau:

    P(E_t | tau)  =  prod_c  P_c(e_c | tau).

This assumption is convenient -- closed-form EIG and a single multiplicative
Bayes update -- but rarely exact: specialists often co-fire on the same
arithmetic discrepancy, stage1 frequently agrees with the
"contradiction-found" stage2 label, etc. Multiplying correlated likelihoods
double-counts evidence and over-concentrates the posterior, which inflates
miscoverage relative to the nominal delta.

Per-channel temperature scaling
-------------------------------
We learn a positive scalar T_c per channel and replace the product fusion
with the tempered product:

    P_joint(E_t | tau)  ~  prod_c  P_c(e_c | tau) ** (1 / T_c).

Equivalently in log-space, the joint log-likelihood is a *weighted* sum of
per-channel log-likelihoods with weights w_c = 1/T_c. T_c > 1 SOFTENS an
over-confident channel; T_c < 1 SHARPENS an under-confident one; T_c = 1
recovers the independent-product fusion.

Why this works
--------------
This is the same trick as Platt / temperature scaling for classifier
calibration (Guo et al., ICML 2017), generalized to multi-channel Bayesian
fusion. Under jointly-correlated channels, the tempered-product fusion is
the maximum-likelihood projection of the true joint onto the exponential
family generated by {log P_c}, with weights {1/T_c} acting as natural
parameters (Wainwright & Jordan 2008, Sec. 3). Fitting T_c by NLL is a
1-D convex problem per coordinate (when others are held fixed), so a few
rounds of coordinate-wise golden-section search converge.

The implementation is pure-Python and standalone; no numpy or scipy.
"""
from __future__ import annotations

import math
from dataclasses import dataclass, field
from typing import Sequence


# ---- Mixer ----

@dataclass(slots=True)
class TemperatureMixer:
    """Per-channel temperature scaling for Bayesian likelihood fusion.

    Use `mixer.temper(likelihood=..., channel=...)` to obtain a tempered
    likelihood vector to feed Posterior.bayes_update. T_c defaults to 1.0
    (= no tempering) for any unlisted channel.
    """

    temperatures: dict[str, float] = field(default_factory=dict)
    meta: dict = field(default_factory=dict)

    @classmethod
    def neutral(cls) -> "TemperatureMixer":
        return cls(temperatures={})

    def __post_init__(self) -> None:
        for c, T in self.temperatures.items():
            if not (T > 0.0):
                raise ValueError(f"temperature for {c!r} must be > 0, got {T}")

    def temper(self, *, likelihood: Sequence[float], channel: str) -> list[float]:
        T = float(self.temperatures.get(channel, 1.0))
        if T == 1.0:
            return [float(v) for v in likelihood]
        if T <= 0.0:
            raise ValueError(f"temperature for {channel} must be positive, got {T}")
        inv = 1.0 / T
        return [max(float(v), 1e-300) ** inv for v in likelihood]

    def temperature(self, channel: str) -> float:
        return float(self.temperatures.get(channel, 1.0))

    def to_dict(self) -> dict:
        return {
            "temperatures": dict(self.temperatures),
            "meta": dict(self.meta),
        }

    @classmethod
    def from_dict(cls, payload: dict) -> "TemperatureMixer":
        temps_raw = payload.get("temperatures") or {}
        temps = {str(k): float(v) for k, v in temps_raw.items()}
        return cls(temperatures=temps, meta=dict(payload.get("meta", {})))


# ---- Calibration data carrier ----

@dataclass(slots=True, frozen=True)
class CalibrationStep:
    """Per-step likelihoods from each channel at one step of one trajectory.

    likelihoods : dict[channel_name -> list[float]]
        Each entry is a length-(T+1) likelihood vector p(e_c | tau = k).
        Channels with no signal at this step can be omitted (treated as
        uniform). Vectors must be aligned across channels (same length).
    """
    likelihoods: dict[str, tuple[float, ...]]


@dataclass(slots=True, frozen=True)
class CalibrationTrajectory:
    """A trajectory of per-step per-channel likelihoods + gold first-mistake index.

    gold_tau : int
        Index into the (T+1)-vector. Use T (i.e., num_steps) for tau=infty.
    prior : tuple[float, ...]
        The starting prior pi_0 that was used during inference. Length T+1.
    """
    prior: tuple[float, ...]
    steps: tuple[CalibrationStep, ...]
    gold_tau: int


# ---- Fitting ----

def _trajectory_neg_log_posterior_at_truth(
    *,
    trajectory: CalibrationTrajectory,
    temperatures: dict[str, float],
) -> float:
    """Negative log posterior mass on the gold tau at the end of one trajectory.

    Computes everything in log-space for numerical stability.
    """
    log_post = [math.log(max(float(p), 1e-300)) for p in trajectory.prior]
    n_hyp = len(log_post)
    for step in trajectory.steps:
        for channel, lik in step.likelihoods.items():
            if len(lik) != n_hyp:
                raise ValueError(
                    f"channel {channel}: likelihood length {len(lik)} != prior length {n_hyp}"
                )
            T = float(temperatures.get(channel, 1.0))
            if T <= 0.0:
                raise ValueError(f"temperature for {channel} must be > 0")
            inv = 1.0 / T
            for k in range(n_hyp):
                log_post[k] += inv * math.log(max(float(lik[k]), 1e-300))
        # log-sum-exp normalize each step for numerical stability
        m = max(log_post)
        lse = m + math.log(sum(math.exp(x - m) for x in log_post))
        log_post = [x - lse for x in log_post]
    return -log_post[trajectory.gold_tau]


def calibration_nll(
    *,
    trajectories: Sequence[CalibrationTrajectory],
    temperatures: dict[str, float],
) -> float:
    """Total negative log likelihood of the gold taus under the joint fusion."""
    return sum(
        _trajectory_neg_log_posterior_at_truth(
            trajectory=tj, temperatures=temperatures
        )
        for tj in trajectories
    )


def _golden_section_min(
    f, lo: float, hi: float, *, tol: float = 1e-3, max_iter: int = 80
) -> float:
    """Minimize a unimodal scalar function f on [lo, hi]. Returns argmin estimate."""
    phi = (1.0 + 5.0 ** 0.5) / 2.0
    invphi = 1.0 / phi
    a, b = float(lo), float(hi)
    c = b - (b - a) * invphi
    d = a + (b - a) * invphi
    fc = f(c)
    fd = f(d)
    for _ in range(max_iter):
        if abs(b - a) < tol:
            break
        if fc < fd:
            b = d
            d = c
            fd = fc
            c = b - (b - a) * invphi
            fc = f(c)
        else:
            a = c
            c = d
            fc = fd
            d = a + (b - a) * invphi
            fd = f(d)
    return 0.5 * (a + b)


def fit_temperatures(
    *,
    trajectories: Sequence[CalibrationTrajectory],
    channels: Sequence[str],
    n_rounds: int = 4,
    log_T_lo: float = -2.0,
    log_T_hi: float = 2.0,
    initial: dict[str, float] | None = None,
) -> TemperatureMixer:
    """Fit per-channel temperatures by coordinate-wise NLL minimization.

    For each channel in turn, hold the others fixed and golden-section search
    log(T_c) in [log_T_lo, log_T_hi]. Repeat for `n_rounds` sweeps.

    Coordinate-wise is sufficient because in log-space the per-channel NLL
    contribution is a positively-weighted sum of convex log-sum-exp terms,
    which is convex in each log-temperature scalar with the others fixed.

    Parameters
    ----------
    trajectories : sequence of CalibrationTrajectory
        At least 1 needed; typically 50+ for stable fitting.
    channels : sequence of str
        Channels to fit. Channels not in this list keep T = initial value
        (or 1.0 if absent).
    initial : dict[str, float] or None
        Starting temperatures. Defaults to 1.0 for all channels.
    """
    if not trajectories:
        raise ValueError("fit_temperatures requires at least one trajectory")
    temps: dict[str, float] = {c: 1.0 for c in channels}
    if initial:
        for c in channels:
            if c in initial and initial[c] > 0.0:
                temps[c] = float(initial[c])

    def objective_at(channel: str, log_T: float) -> float:
        trial = dict(temps)
        trial[channel] = math.exp(log_T)
        return calibration_nll(trajectories=trajectories, temperatures=trial)

    for _round in range(n_rounds):
        for channel in channels:
            log_T_star = _golden_section_min(
                lambda x, _c=channel: objective_at(_c, x),
                log_T_lo,
                log_T_hi,
            )
            temps[channel] = math.exp(log_T_star)

    final_nll = calibration_nll(trajectories=trajectories, temperatures=temps)
    return TemperatureMixer(
        temperatures=temps,
        meta={
            "type": "fit_temperatures",
            "n_trajectories": len(trajectories),
            "channels": list(channels),
            "n_rounds": n_rounds,
            "final_nll": final_nll,
        },
    )
