"""Tests for the anytime-valid e-process stopping rule."""
from __future__ import annotations

import math
import random

from mathchecker.prism.conformal import calibrate_split_conformal
from mathchecker.prism.eprocess import EProcessSchedule, default_eprocess
from mathchecker.prism.infer import PrismEvidence, prism_infer
from mathchecker.prism.posterior import length_prior


# ---- construction + basic semantics ----

def test_eprocess_threshold_bonferroni() -> None:
    sched = EProcessSchedule(
        delta=0.1,
        prior=[0.2, 0.3, 0.5],
        num_steps=2,
        multiplicity="bonferroni",
    )
    # threshold = (T+1)/delta = 3 / 0.1 = 30
    assert sched.threshold == 30.0


def test_eprocess_threshold_per_target_default() -> None:
    sched = EProcessSchedule(
        delta=0.1,
        prior=[0.5, 0.5],
        num_steps=1,
    )
    # Default is per_target -> threshold = 1/delta.
    assert sched.threshold == 10.0
    assert sched.multiplicity == "per_target"


def test_eprocess_threshold_none_aliases_per_target() -> None:
    sched = EProcessSchedule(
        delta=0.1,
        prior=[0.5, 0.5],
        num_steps=1,
        multiplicity="none",
    )
    assert sched.threshold == 10.0


def test_eprocess_rejects_bad_delta() -> None:
    for bad in (-0.1, 0.0, 1.0, 1.5):
        try:
            EProcessSchedule(delta=bad, prior=[0.5, 0.5], num_steps=1)
        except ValueError:
            continue
        raise AssertionError(f"delta={bad} should have raised")


def test_eprocess_rejects_prior_length_mismatch() -> None:
    try:
        EProcessSchedule(delta=0.1, prior=[0.5, 0.5], num_steps=5)
    except ValueError:
        return
    raise AssertionError("prior length mismatch should raise")


def test_eprocess_normalizes_prior() -> None:
    sched = EProcessSchedule(delta=0.1, prior=[1.0, 1.0, 2.0], num_steps=2)
    assert math.isclose(sum(sched.prior), 1.0, abs_tol=1e-9)
    assert math.isclose(sched.prior[2], 0.5, abs_tol=1e-9)


def test_evalue_is_posterior_over_prior() -> None:
    sched = EProcessSchedule(delta=0.1, prior=[0.2, 0.3, 0.5], num_steps=2)
    post = [0.1, 0.6, 0.3]
    assert math.isclose(sched.evalue_at(posterior_probs=post, hypothesis_index=1), 0.6 / 0.3, abs_tol=1e-9)
    assert math.isclose(sched.evalue_at(posterior_probs=post, hypothesis_index=0), 0.1 / 0.2, abs_tol=1e-9)


# ---- Ville-inequality coverage under H_0 ----

def test_eprocess_per_target_ville_bound_under_null() -> None:
    """For a fixed target hypothesis k_fixed, Ville's inequality guarantees
    P( sup_t M_t(k_fixed) >= 1/delta ) <= delta when the posterior is
    generated by a process that is exchangeable with respect to k_fixed (so
    {M_t(k_fixed)} is a non-negative martingale starting at 1).

    We construct synthetic posterior trajectories where the per-step
    likelihood ratios for k_fixed are mean-1 (true martingale) and check
    that the empirical rate of crossing 1/delta is below delta.
    """
    random.seed(2024)
    num_steps = 5
    delta = 0.1
    prior = length_prior(num_steps, p_no_error=0.4)
    sched = EProcessSchedule(
        delta=delta,
        prior=prior,
        num_steps=num_steps,
        multiplicity="per_target",
    )
    k_fixed = 2  # we'll test miscoverage for THIS target only

    n_trials = 5000
    cross_count = 0
    for _ in range(n_trials):
        post = list(prior)
        m_path_max = 1.0
        for _t in range(num_steps + 2):  # extra steps to give the e-process time
            # Per-step likelihood ratio l_t(k) sampled so that
            # E[l_t(k_fixed)] = 1 (martingale property for k_fixed).
            # Use lognormal with mean-correcting offset.
            lik = []
            for k in range(num_steps + 1):
                # All hypotheses get same noise distribution (exchangeable
                # null). Under this null, {M_t(k)} is mean-1 supermartingale.
                lik.append(math.exp(random.gauss(-0.5, 1.0)))
            unnorm = [p * l for p, l in zip(post, lik)]
            total = sum(unnorm)
            if total <= 0:
                continue
            post = [u / total for u in unnorm]
            m_k = sched.evalue_at(posterior_probs=post, hypothesis_index=k_fixed)
            if m_k > m_path_max:
                m_path_max = m_k
        if m_path_max >= 1.0 / delta:
            cross_count += 1

    cross_rate = cross_count / n_trials
    # Ville bound is conservative; finite-sample noise makes this even more so.
    assert cross_rate <= delta + 0.02, (
        f"per-target sup-crossing rate {cross_rate:.4f} exceeds delta {delta}"
    )


# ---- comparison vs split-conformal Bonferroni ----

def test_eprocess_commits_when_posterior_dominates_prior() -> None:
    """E-process fires once M_t(k) = pi_t(k)/pi_0(k) crosses 1/delta=10.
    With a uniform-ish prior pi_0(k)=0.05 and posterior 0.6 on k, M=12 >= 10
    so commit triggers."""
    num_steps = 19  # 20 hypotheses incl tau=infty -> uniform prior = 0.05 each
    prior = [1.0 / 20] * 20
    ep = EProcessSchedule(delta=0.1, prior=prior, num_steps=num_steps)
    post = [0.6] + [(1.0 - 0.6) / 19] * 19
    s = sum(post); post = [p / s for p in post]
    argmax = max(range(len(post)), key=lambda i: post[i])
    assert argmax == 0
    assert ep.should_commit(posterior_probs=post, argmax_index=argmax)


def test_eprocess_does_not_commit_when_posterior_matches_prior() -> None:
    """If the posterior equals the prior (no information gain), every
    M_t(k) = 1 < threshold = (T+1)/delta. Cannot commit."""
    num_steps = 4
    prior = length_prior(num_steps, p_no_error=0.4)
    ep = EProcessSchedule(delta=0.1, prior=prior, num_steps=num_steps)
    post = list(prior)
    argmax = max(range(len(post)), key=lambda i: post[i])
    assert not ep.should_commit(posterior_probs=post, argmax_index=argmax)


# ---- end-to-end wiring through prism_infer ----

def test_prism_infer_accepts_eprocess_schedule() -> None:
    """prism_infer must accept an EProcessSchedule in place of ConformalSchedule
    and produce the same algorithmic structure (loop runs, commits, etc.)."""
    num_steps = 4

    def evidence(t: int) -> PrismEvidence:
        if t == 2:
            return PrismEvidence(
                step_index=t,
                principle_labels=("contradiction-found", "contradiction-found", "contradiction-found"),
                specialist_emissions={"alternative_route_verifier_tool": (0.95, 0.05)},
            )
        return PrismEvidence(
            step_index=t,
            principle_labels=("correct-and-aligned",) * 3,
        )

    ep = default_eprocess(num_steps=num_steps, delta=0.1, p_no_error=0.4)
    result = prism_infer(
        num_steps=num_steps,
        evidence_at_step=evidence,
        schedule=ep,
    )
    assert result.pred_first_mistake_index == 2


def test_eprocess_commits_earlier_when_target_is_rare_under_prior() -> None:
    """The e-process commits earlier than the conformal max-mass floor when
    the target hypothesis is RARE under the prior, because it normalizes by
    pi_0(k). A posterior mass of 0.5 on a hypothesis with prior 0.02 yields
    e-value 25, well above 1/delta=10, while 0.5 < 1-delta=0.9 (conformal
    floor never fires).
    """
    num_steps = 6
    prior = [0.02, 0.02, 0.02, 0.02, 0.42, 0.02, 0.48]  # tau=4 and tau=infty likely
    sched = EProcessSchedule(delta=0.1, prior=prior, num_steps=num_steps)
    # Posterior puts 0.5 on the rare hypothesis tau=0.
    post = [0.5] + [0.5 / 6] * 6
    s = sum(post); post = [p / s for p in post]
    argmax = 0
    # E-value: 0.5 / 0.02 = 25 >= threshold 10. Should commit.
    assert sched.should_commit(posterior_probs=post, argmax_index=argmax)
    # Conformal default floor: alpha = 1-delta = 0.9. Max posterior = 0.5 < 0.9.
    # Conformal would NOT commit in this regime.
    assert max(post) < 0.9


def test_default_eprocess_uses_length_prior() -> None:
    sched = default_eprocess(num_steps=5, delta=0.1, p_no_error=0.4)
    expected_prior = length_prior(5, p_no_error=0.4)
    for a, b in zip(sched.prior, expected_prior):
        assert math.isclose(a, b, abs_tol=1e-9)


def test_eprocess_round_trip_via_to_from_dict() -> None:
    sched = EProcessSchedule(
        delta=0.05,
        prior=[0.1, 0.2, 0.3, 0.4],
        num_steps=3,
        multiplicity="bonferroni",
        meta={"note": "test"},
    )
    payload = sched.to_dict()
    restored = EProcessSchedule.from_dict(payload)
    assert math.isclose(restored.delta, sched.delta, abs_tol=1e-12)
    assert restored.multiplicity == sched.multiplicity
    for a, b in zip(restored.prior, sched.prior):
        assert math.isclose(a, b, abs_tol=1e-9)
